application/models/user.py
from application import db
from flask_login import UserMixin
from datetime import datetime


class User(db.Model, UserMixin):
    __tablename__ = 'users'  

    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(150), unique=True, nullable=False)
    password = db.Column(db.String(255), nullable=False)
    first_name = db.Column(db.String(150), nullable=False)
    last_name = db.Column(db.String(150), nullable=False)
    gender = db.Column(db.String(50), nullable=False)
    address = db.Column(db.String(255), nullable=False)
    zip_code = db.Column(db.String(20), nullable=False)
    created_at = db.Column(db.DateTime, default=datetime.utcnow, nullable=False)
    updated_at = db.Column(db.DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)

    posts = db.relationship('Post', backref='author', lazy=True)

application/forms/user_form.py
from flask_wtf import FlaskForm
from wtforms.validators import Email
from wtforms import StringField, PasswordField
from wtforms.validators import DataRequired, Email, Length, EqualTo

    
class UpdateUserForm(FlaskForm):
    first_name = StringField('First Name', validators=[
        DataRequired(message="First name is required."),
        Length(min=2, max=150, message="First name must be between 2 and 150 characters.")
    ])
    last_name = StringField('Last Name', validators=[
        DataRequired(message="Last name is required."),
        Length(min=2, max=150, message="Last name must be between 2 and 150 characters.")
    ])
    email = StringField('Email', validators=[
        DataRequired(message="Email address is required."),
        Email(message="Please enter a valid email address.")
    ])
    address = StringField('Address', validators=[
        DataRequired(message="Address is required."),
        Length(min=10, max=255, message="Address must be between 10 and 255 characters.")
    ])
    zip_code = StringField('Zip Code', validators=[
        DataRequired(message="Zip code is required."),
        Length(min=5, max=20, message="Zip code must be between 5 and 20 characters.")
    ])
    gender = StringField('Gender', validators=[
        DataRequired(message="Please select your gender.")
    ])
    

class PasswordForm(FlaskForm):
    password = PasswordField('Password', validators=[
        DataRequired(message="Password is required."),
        Length(min=8, message="Password must be at least 8 characters long.")
    ])
    confirm_password = PasswordField('Confirm Password', validators=[
        DataRequired(message="Please confirm your password."),
        EqualTo('password', message="Passwords must match.")
    ])
    old_password = PasswordField('Old Password', validators=[
        DataRequired(message="Old Password is required.")
    ])
    
    
class DeleteUserForm(FlaskForm):
    """A form for CSRF-protected delete actions."""
    pass 

application/views/home.py
from flask import Blueprint, render_template, flash, redirect, url_for,request
from flask_login import login_required, current_user
from application.forms.user_form import UpdateUserForm, PasswordForm
from application.forms.auth_form import RegistrationForm
from application.services.user_service import UserService
from werkzeug.security import check_password_hash
from application.services.post_service import PostService

home = Blueprint('home', __name__)


@home.route('/', methods=['GET'])
def home_page():
    form = RegistrationForm()
    return render_template('auth/login.html', form=form)


@home.route('/dashboard', methods=['GET'])
@login_required
def dashboard_page():
    dash_stats = {
        'total_posts': len(PostService.get_all_posts()),
        'total_users': len(UserService.get_all_users()),
        'total_messages': 0,
    }
    return render_template('home/dashboard.html', dash_stats=dash_stats)


@home.route('/messages', methods=['GET'])
@login_required
def messages_page():
    return render_template('home/messages.html')


@home.route('/profile')
@login_required
def profile():
    form = UpdateUserForm()
    return render_template('user/profile.html', form=form, user=current_user)


@home.route('/profile', methods=['GET', 'POST'])
@login_required
def update_profile():
     form = UpdateUserForm()
     if request.method == 'POST' and form.validate_on_submit():  
        data = {
            'first_name': form.first_name.data,
            'last_name': form.last_name.data,
            'email': form.email.data,
            'address': form.address.data,
            'zip_code': form.zip_code.data,
            'gender': form.gender.data
        }
        profile_updated = UserService.update_user(current_user.id, data)
        if profile_updated:
            flash(message='Profile details updated successfully!', category='success')
            return redirect(url_for('home.profile'))
        else:
            flash(message='Profile details updation failed. Please try again.', category='danger')
            return redirect(url_for('home.profile'))
    
     return render_template('home/profile.html', form=form)



@home.route('/password')
@login_required
def change_password():
    form = PasswordForm()
    return render_template('user/password.html', form=form)



@home.route('/password', methods=['GET', 'POST'])
@login_required
def update_password():
     form = PasswordForm()
     if request.method == 'POST' and form.validate_on_submit():  
        
        new_password = form.password.data
        old_password = form.old_password.data
        current_password = current_user.password
        
        if check_password_hash(current_password, old_password):            
            password_updated = UserService.update_user_password(current_user.id, new_password)
            if password_updated:
                flash(message='Account password updated successfully!', category='success')
                return redirect(url_for('home.dashboard_page'))
            else:
                flash(message='Password updation failed. Please try again.', category='danger')
        else:
           flash(message='The password you have entered does not match the existing one.', category='danger')
     
     return render_template('user/password.html', form=form)

application/views/user.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from application import db   #means from __init__.py import db
from flask_login import login_required, logout_user, current_user
from application.forms.user_form import UpdateUserForm, DeleteUserForm
from application.services.user_service import UserService

user = Blueprint('user', __name__)

@user.route('/')
@login_required
def list_users():
    form = DeleteUserForm()
    users = UserService.get_all_users()
    return render_template('user/users.html', users=users, form=form)


@user.route('/<int:user_id>')
@login_required
def show_user(user_id):
    user = UserService.get_user_by_id(user_id)
    return render_template('user/show.html', user=user)


@user.route('/<int:user_id>/edit')
@login_required
def edit_user(user_id):
    form = UpdateUserForm()
    user = UserService.get_user_by_id(user_id)
    
    return render_template('user/edit.html', user=user, form=form)


@user.route('/<int:user_id>/edit', methods=['GET', 'POST'])
@login_required
def update_user(user_id):
    form = UpdateUserForm()
    user = UserService.get_user_by_id(user_id)
    
    if request.method == 'POST' and form.validate_on_submit():  
        data = {
            'first_name': form.first_name.data,
            'last_name': form.last_name.data,
            'email': form.email.data,
            'address': form.address.data,
            'zip_code': form.zip_code.data,
            'gender': form.gender.data
        }
        user_updated = UserService.update_user(user_id, data)
        if user_updated:
            flash(message='User details updated successfully!', category='success')
            return redirect(url_for('user.list_users'))
        else:
            flash(message='User details updation failed. Please try again.', category='danger')
            return redirect(url_for('user.list_users'))
    
    return render_template('user/edit.html', user=user, form=form)



@user.route('/<int:user_id>/delete', methods=['POST'])
@login_required
def delete_user(user_id):
    user = UserService.get_user_by_id(user_id)

    if user.id == current_user.id:
        flash('You are not authorized to delete your own details.', 'danger')
        return redirect(url_for('user.list_users'))

    user_deleted = UserService.delete_user(user_id)
    if user_deleted:
        flash('User deleted successfully!', 'success')
        return redirect(url_for('user.list_users'))
    else:
        flash('There was a problem while deleting user. Please try again!', 'danger')
        return redirect(url_for('user.list_users'))

application/templates/user/edit.html
{% extends "layouts/base.html" %} {% block title %}Manage Users{% endblock %} {%
block content %}
<div class="content">
  <div class="container">
    <div class="row">
      <div class="col-md-12 page-header">
        <h2 class="page-title">Edit Users</h2>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12 page-header">
        <div class="col-md-12 col-lg-12">
          <div class="card">
            <div class="card-header">
              {{ user.first_name }} {{ user.last_name }}
            </div>
            <div class="card-body">
              <form
                action="{{ url_for('user.update_user', user_id=user.id) }}"
                method="post"
                autocomplete="off"
              >
                {{ form.hidden_tag() }}
                <div class="row">
                  <div class="col-sm-6 mb-3 text-start">
                    <label for="first_name" class="form-label"
                      >First Name</label
                    >
                    <input
                      type="text"
                      name="first_name"
                      value="{{ user.first_name }}"
                      class="form-control {% if form.first_name.errors %}is-invalid{% endif %}"
                      placeholder="Enter your first name"
                      required
                      autofocus
                    />
                    {% for error in form.first_name.errors %}
                    <div class="invalid-feedback">{{ error }}</div>
                    {% endfor %}
                  </div>

                  <div class="col-sm-6 mb-3 text-start">
                    <label for="last_name" class="form-label">Last Name</label>
                    <input
                      type="text"
                      name="last_name"
                      value="{{ user.last_name }}"
                      class="form-control {% if form.last_name.errors %}is-invalid{% endif %}"
                      placeholder="Enter your last name"
                      required
                    />
                    {% for error in form.last_name.errors %}
                    <div class="invalid-feedback">{{ error }}</div>
                    {% endfor %}
                  </div>

                  <div class="col-sm-6 mb-3 text-start">
                    <label for="email" class="form-label">Email Address</label>
                    <input
                      type="email"
                      name="email"
                      value="{{ user.email }}"
                      class="form-control {% if form.email.errors %}is-invalid{% endif %}"
                      placeholder="Enter your email"
                      required
                    />
                    {% for error in form.email.errors %}
                    <div class="invalid-feedback">{{ error }}</div>
                    {% endfor %}
                  </div>

                  <div class="col-sm-6 mb-3 text-start">
                    <label for="address" class="form-label">Address</label>
                    <input
                      type="text"
                      name="address"
                      value="{{ user.address }}"
                      class="form-control {% if form.address.errors %}is-invalid{% endif %}"
                      placeholder="Enter your address"
                    />
                    {% for error in form.address.errors %}
                    <div class="invalid-feedback">{{ error }}</div>
                    {% endfor %}
                  </div>

                  <div class="col-sm-6 mb-3 text-start">
                    <label for="gender" class="form-label">Gender</label>
                    <select
                      name="gender"
                      class="form-select {% if form.gender.errors %}is-invalid{% endif %}"
                      required
                    >
                      <option value="{{ user.gender }}" selected>
                        {{ user.gender }}
                      </option>
                      <option value="male">Male</option>
                      <option value="female">Female</option>
                      <option value="other">Other</option>
                    </select>
                    {% for error in form.gender.errors %}
                    <div class="invalid-feedback">{{ error }}</div>
                    {% endfor %}
                  </div>

                  <div class="col-sm-6 mb-3 text-start">
                    <label for="zip_code" class="form-label">Zip Code</label>
                    <input
                      type="text"
                      name="zip_code"
                      value="{{ user.zip_code }}"
                      class="form-control {% if form.zip_code.errors %}is-invalid{% endif %}"
                      placeholder="Enter your zip code"
                    />
                    {% for error in form.zip_code.errors %}
                    <div class="invalid-feedback">{{ error }}</div>
                    {% endfor %}
                  </div>
                </div>
                <button type="submit" class="btn btn-primary mb-4">
                  Update User Details
                </button>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

application/templates/user/password.html
{% extends "layouts/base.html" %} {% block title %}Update Profile{% endblock %}
{% block content %}
<div class="content">
  <div class="container">
    <div class="row">
      <div class="col-md-12 page-header">
        <h2 class="page-title">Update Password</h2>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12 page-header">
        <div class="col-md-12 col-lg-12">
          <div class="card">
            <div class="card-header">Update Account Password</div>
            <div class="card-body">
              <form
                action="{{ url_for('home.update_password') }}"
                method="post"
                autocomplete="off"
              >
                {{ form.hidden_tag() }}
                <div class="row">
                  <div class="col-sm-4 mb-3 text-start">
                    <label for="password" class="form-label"
                      >Old Password</label
                    >
                    <input
                      type="password"
                      name="old_password"
                      class="form-control {% if form.old_password.errors %}is-invalid{% endif %}"
                      placeholder="Enter your old password"
                      required
                    />
                    {% for error in form.password.errors %}
                    <div class="invalid-feedback">{{ error }}</div>
                    {% endfor %}
                  </div>

                  <div class="col-sm-4 mb-3 text-start">
                    <label for="password" class="form-label"
                      >New Password</label
                    >
                    <input
                      type="password"
                      name="password"
                      class="form-control {% if form.password.errors %}is-invalid{% endif %}"
                      placeholder="Enter your new password"
                      required
                    />
                    {% for error in form.password.errors %}
                    <div class="invalid-feedback">{{ error }}</div>
                    {% endfor %}
                  </div>

                  <div class="col-sm-4 mb-3 text-start">
                    <label for="confirm_password" class="form-label"
                      >Confirm New Password</label
                    >
                    <input
                      type="password"
                      name="confirm_password"
                      class="form-control {% if form.confirm_password.errors %}is-invalid{% endif %}"
                      placeholder="Confirm your new password"
                      required
                    />
                    {% for error in form.confirm_password.errors %}
                    <div class="invalid-feedback">{{ error }}</div>
                    {% endfor %}
                  </div>
                </div>
                <button type="submit" class="btn btn-primary mb-4">
                  Update Password
                </button>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

application/templates/user/profile.html
{% extends "layouts/base.html" %} {% block title %}Update Profile{% endblock %}
{% block content %}
<div class="content">
  <div class="container">
    <div class="row">
      <div class="col-md-12 page-header">
        <h2 class="page-title">Edit Profile</h2>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12 page-header">
        <div class="col-md-12 col-lg-12">
          <div class="card">
            <div class="card-header">
              {{ current_user.first_name }} {{ current_user.last_name }}
            </div>
            <div class="card-body">
              <form
                action="{{ url_for('home.update_profile') }}"
                method="post"
                autocomplete="off"
              >
                {{ form.hidden_tag() }}
                <div class="row">
                  <div class="col-sm-6 mb-3 text-start">
                    <label for="first_name" class="form-label"
                      >First Name</label
                    >
                    <input
                      type="text"
                      name="first_name"
                      value="{{ current_user.first_name }}"
                      class="form-control {% if form.first_name.errors %}is-invalid{% endif %}"
                      placeholder="Enter your first name"
                      required
                      autofocus
                    />
                    {% for error in form.first_name.errors %}
                    <div class="invalid-feedback">{{ error }}</div>
                    {% endfor %}
                  </div>

                  <div class="col-sm-6 mb-3 text-start">
                    <label for="last_name" class="form-label">Last Name</label>
                    <input
                      type="text"
                      name="last_name"
                      value="{{ current_user.last_name }}"
                      class="form-control {% if form.last_name.errors %}is-invalid{% endif %}"
                      placeholder="Enter your last name"
                      required
                    />
                    {% for error in form.last_name.errors %}
                    <div class="invalid-feedback">{{ error }}</div>
                    {% endfor %}
                  </div>

                  <div class="col-sm-6 mb-3 text-start">
                    <label for="email" class="form-label">Email Address</label>
                    <input
                      type="email"
                      name="email"
                      value="{{ current_user.email }}"
                      class="form-control {% if form.email.errors %}is-invalid{% endif %}"
                      placeholder="Enter your email"
                      required
                    />
                    {% for error in form.email.errors %}
                    <div class="invalid-feedback">{{ error }}</div>
                    {% endfor %}
                  </div>

                  <div class="col-sm-6 mb-3 text-start">
                    <label for="address" class="form-label">Address</label>
                    <input
                      type="text"
                      name="address"
                      value="{{ current_user.address }}"
                      class="form-control {% if form.address.errors %}is-invalid{% endif %}"
                      placeholder="Enter your address"
                    />
                    {% for error in form.address.errors %}
                    <div class="invalid-feedback">{{ error }}</div>
                    {% endfor %}
                  </div>

                  <div class="col-sm-6 mb-3 text-start">
                    <label for="gender" class="form-label">Gender</label>
                    <select
                      name="gender"
                      class="form-select {% if form.gender.errors %}is-invalid{% endif %}"
                      required
                    >
                      <option value="{{ current_user.gender }}" selected>
                        {{ current_user.gender }}
                      </option>
                      <option value="male">Male</option>
                      <option value="female">Female</option>
                      <option value="other">Other</option>
                    </select>
                    {% for error in form.gender.errors %}
                    <div class="invalid-feedback">{{ error }}</div>
                    {% endfor %}
                  </div>

                  <div class="col-sm-6 mb-3 text-start">
                    <label for="zip_code" class="form-label">Zip Code</label>
                    <input
                      type="text"
                      name="zip_code"
                      value="{{ current_user.zip_code }}"
                      class="form-control {% if form.zip_code.errors %}is-invalid{% endif %}"
                      placeholder="Enter your zip code"
                    />
                    {% for error in form.zip_code.errors %}
                    <div class="invalid-feedback">{{ error }}</div>
                    {% endfor %}
                  </div>
                </div>
                <button type="submit" class="btn btn-primary mb-4">
                  Update Profile
                </button>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

application/templates/user/show.html
{% extends "layouts/base.html" %} {% block title %}Show User{% endblock %} {%
block content %}
<div class="content">
  <div class="container">
    <div class="row">
      <div class="col-md-12 page-header">
        <h2 class="page-title">Show User</h2>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12 page-header">
        <div class="col-md-12 col-lg-12">
          <div class="card">
            <div class="card-header">
              {{ user.first_name }} {{ user.last_name }}
            </div>
            <div class="card-body">
              <div class="row">
                <div class="col-sm-6 mb-3 text-start">
                  <label for="first_name" class="form-label">First Name</label>
                  <input
                    type="text"
                    name="first_name"
                    value="{{ user.first_name }}"
                    class="form-control"
                    placeholder="Enter your first name"
                    required
                    autofocus
                  />
                </div>

                <div class="col-sm-6 mb-3 text-start">
                  <label for="last_name" class="form-label">Last Name</label>
                  <input
                    type="text"
                    name="last_name"
                    value="{{ user.last_name }}"
                    class="form-control"
                    placeholder="Enter your last name"
                    required
                  />
                </div>

                <div class="col-sm-6 mb-3 text-start">
                  <label for="email" class="form-label">Email Address</label>
                  <input
                    type="email"
                    name="email"
                    value="{{ user.email }}"
                    class="form-control"
                    placeholder="Enter your email"
                    required
                  />
                </div>

                <div class="col-sm-6 mb-3 text-start">
                  <label for="address" class="form-label">Address</label>
                  <input
                    type="text"
                    name="address"
                    value="{{ user.address }}"
                    class="form-control"
                    placeholder="Enter your address"
                  />
                </div>

                <div class="col-sm-6 mb-3 text-start">
                  <label for="gender" class="form-label">Gender</label>
                  <select
                    name="gender"
                    class="form-select"
                    required
                  >
                    <option value="{{ user.gender }}" selected>
                      {{ user.gender }}
                    </option>
                    <option value="male">Male</option>
                    <option value="female">Female</option>
                    <option value="other">Other</option>
                  </select>
                </div>

                <div class="col-sm-6 mb-3 text-start">
                  <label for="zip_code" class="form-label">Zip Code</label>
                  <input
                    type="text"
                    name="zip_code"
                    value="{{ user.zip_code }}"
                    class="form-control"
                    placeholder="Enter your zip code"
                  />
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

application/templates/user/users.html
{% extends "layouts/base.html" %} {% block title %} Manage Users {% endblock %}
{%block content %}
<div class="content">
  <div class="container">
    <div class="row">
      <div class="col-md-12 page-header">
        <h2 class="page-title">Manage Users</h2>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12 page-header">
        <div class="col-md-12 col-lg-12">
          <div class="card">
            <div class="card-header">Manage Users</div>
            <div class="card-body">
              <p class="card-title"></p>
              <table
                class="table table-striped table-bordered table-hover"
                id="dataTables-example"
                width="100%"
              >
                <thead>
                  <tr>
                    <th>ID</th>
                    <th>First Name</th>
                    <th>Last Name</th>
                    <th>Gender</th>
                    <th>Address</th>
                    <th>Zip Code</th>
                    <th>Action</th>
                  </tr>
                </thead>
                <tbody>
                  {% for user in users %}
                  <tr>
                    <td>{{ loop.index }}</td>
                    <td>{{ user.first_name }}</td>
                    <td>{{ user.last_name }}</td>
                    <td>{{ user.gender }}</td>
                    <td>{{ user.address }}</td>
                    <td>{{ user.zip_code }}</td>
                    <td>
                      <div class="margin btn-group">
                        <a
                          href="{{ url_for('user.show_user', user_id=user.id) }}"
                          class="btn btn-sm btn-info"
                          title="Click to view user details"
                        >
                          <i class="fa fa-bars"></i>
                        </a>
                        <a
                          href="{{ url_for('user.edit_user', user_id=user.id) }}"
                          class="btn btn-sm btn-primary"
                          title="Click to edit user details"
                        >
                          <i class="fa fa-edit"></i>
                        </a>

                        <form
                          action="{{ url_for('user.delete_user', user_id=user.id) }}"
                          method="POST"
                          style="display: inline"
                          onsubmit="return confirm('Are you sure you want to delete this user?');"
                        >
                          {{ form.hidden_tag() }}
                          <button
                            type="submit"
                            class="btn btn-sm btn-danger"
                            title="Click to delete user"
                          >
                            <i class="fa fa-trash"></i>
                          </button>
                        </form>
                      </div>
                    </td>
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}