application/views/auth.py
from itsdangerous import URLSafeTimedSerializer, BadSignature, SignatureExpired
from flask import Blueprint, render_template, request, flash, redirect, url_for, current_app
from flask_login import login_user, login_required, logout_user, current_user
from flask_mail import Message
from werkzeug.security import check_password_hash
from application.services.user_service import UserService
from application.forms.auth_form import RegistrationForm, LoginForm, ForgotPasswordForm, ResetPasswordForm
from application import mail

auth = Blueprint('auth', __name__)


@auth.route('/login', methods=['GET'])
def login_page():
    form = LoginForm()
    return render_template('auth/login.html', form=form)


@auth.route('/login', methods=['POST'])
def login_handler():
    form = LoginForm()  
    if request.method == 'POST' and form.validate_on_submit():
        email = form.email.data
        password = form.password.data
        remember_me = form.remember.data  

        user = UserService.get_user_by_email(email)
        if user:
            if check_password_hash(user.password, password):
                flash('Logged in successfully!', category='success')
                login_user(user, remember=remember_me)
                return redirect(url_for('home.dashboard_page'))
            else:
                flash('Incorrect password, try again.', category='danger') 
        else:
            flash('Email address does not exist.', category='danger') 
            
    return render_template('auth/login.html', form=form)


@auth.route('/register', methods=['GET'])
def register_page():
    form = RegistrationForm()
    return render_template('auth/register.html', form=form)


@auth.route('/register', methods=['GET', 'POST'])
def register_user():
    form = RegistrationForm()

    if request.method == 'POST' and form.validate_on_submit():  
        data = {
            'first_name': form.first_name.data,
            'last_name': form.last_name.data,
            'email': form.email.data,
            'password': form.password.data,
            'address': form.address.data,
            'zip_code': form.zip_code.data,
            'gender': form.gender.data
        }
        user = UserService.create_user(data)
        if user:
            flash(message='Your registration was successful. Please proceed to login!', category='success')
            return redirect(url_for('auth.login_page'))
        else:
            flash(message='Registration failed. Please try again.', category='danger')
            return redirect(url_for('auth.register_page'))
    
    return render_template('auth/register.html', form=form)
    

@auth.route('/forgot-password', methods=['GET'])
def forgot_password_page():
    form = RegistrationForm()
    return render_template('auth/forgot_password.html', form=form)


@auth.route('/forgot-password', methods=['POST'])
def send_password_reset_link():
    form = ForgotPasswordForm()  

    if request.method == 'POST' and form.validate_on_submit():
        email = form.email.data
        user = UserService.get_user_by_email(email)

        if user:
            try:
                token = UserService.generate_reset_token(user.email)
                UserService.send_reset_email(user.email, token)
                flash('A password reset link has been sent to your email.', category='success')
                return redirect(url_for('auth.login_page'))
            except Exception as e:
                current_app.logger.error(f"Error sending reset email: {str(e)}")
                flash('An error occurred. Please try again later.', category='danger')
        else:
            flash('No account found with that email. Please try again.', category='warning')

    return render_template('auth/forgot_password.html', form=form)


@auth.route('/reset-password/<token>', methods=['GET'])
def reset_password_page(token):
    form = ResetPasswordForm()
    return render_template('auth/reset_password.html', token=token, form=form)


@auth.route('/reset-password/<token>', methods=['POST'])
def reset_user_password(token):
    
    form = ResetPasswordForm()
    if request.method == 'POST' and form.validate_on_submit():
        password = form.password.data

        try:
            serializer = URLSafeTimedSerializer(current_app.config['SECRET_KEY'])
            email = serializer.loads(
                token,
                salt=current_app.config['PASSWORD_RESET_SALT'],
                max_age=3600  # 1 hour expiry
            )
        except SignatureExpired:
            flash("The password reset link has expired.", category="warning")
            return redirect(url_for('auth.forgot_password_page'))
        except BadSignature:
            flash("Invalid or corrupted token.", category="danger")
            return redirect(url_for('auth.forgot_password_page'))

        user = UserService.get_user_by_email(email)
        if user:
            UserService.update_user_password(user.id, password)
            flash("Your password has been updated successfully.", category="success")
            return redirect(url_for('auth.login_page'))
        else:
            flash("No account found for this reset link.", category="danger")
            return redirect(url_for('auth.forgot_password_page'))

    return render_template('auth/reset_password.html', form=form, token=token)


@auth.route('/logout')
@login_required
def logout_handler():
    logout_user()
    flash('You are logged out successfully!', category='success')
    return redirect(url_for('auth.login_page'))

application/views/home.py
from flask import Blueprint, render_template, flash, redirect, url_for,request
from flask_login import login_required, current_user
from application.forms.user_form import UpdateUserForm, PasswordForm
from application.forms.auth_form import RegistrationForm
from application.services.user_service import UserService
from werkzeug.security import check_password_hash
from application.services.post_service import PostService

home = Blueprint('home', __name__)


@home.route('/', methods=['GET'])
def home_page():
    form = RegistrationForm()
    return render_template('auth/login.html', form=form)


@home.route('/dashboard', methods=['GET'])
@login_required
def dashboard_page():
    dash_stats = {
        'total_posts': len(PostService.get_all_posts()),
        'total_users': len(UserService.get_all_users()),
        'total_messages': 0,
    }
    return render_template('home/dashboard.html', dash_stats=dash_stats)


@home.route('/messages', methods=['GET'])
@login_required
def messages_page():
    return render_template('home/messages.html')


@home.route('/profile')
@login_required
def profile():
    form = UpdateUserForm()
    return render_template('user/profile.html', form=form, user=current_user)


@home.route('/profile', methods=['GET', 'POST'])
@login_required
def update_profile():
     form = UpdateUserForm()
     if request.method == 'POST' and form.validate_on_submit():  
        data = {
            'first_name': form.first_name.data,
            'last_name': form.last_name.data,
            'email': form.email.data,
            'address': form.address.data,
            'zip_code': form.zip_code.data,
            'gender': form.gender.data
        }
        profile_updated = UserService.update_user(current_user.id, data)
        if profile_updated:
            flash(message='Profile details updated successfully!', category='success')
            return redirect(url_for('home.profile'))
        else:
            flash(message='Profile details updation failed. Please try again.', category='danger')
            return redirect(url_for('home.profile'))
    
     return render_template('home/profile.html', form=form)



@home.route('/password')
@login_required
def change_password():
    form = PasswordForm()
    return render_template('user/password.html', form=form)



@home.route('/password', methods=['GET', 'POST'])
@login_required
def update_password():
     form = PasswordForm()
     if request.method == 'POST' and form.validate_on_submit():  
        
        new_password = form.password.data
        old_password = form.old_password.data
        current_password = current_user.password
        
        if check_password_hash(current_password, old_password):            
            password_updated = UserService.update_user_password(current_user.id, new_password)
            if password_updated:
                flash(message='Account password updated successfully!', category='success')
                return redirect(url_for('home.dashboard_page'))
            else:
                flash(message='Password updation failed. Please try again.', category='danger')
        else:
           flash(message='The password you have entered does not match the existing one.', category='danger')
     
     return render_template('user/password.html', form=form)

application/templates/layouts/partials/alerts.html
{% with messages = get_flashed_messages(with_categories=true) %} {% if messages
%} {% for category, message in messages %} {% if category == 'danger' %}
<div class="alert alert-danger alert-dismissible fade show" role="alert">
  {{ message }}
  <button
    type="button"
    class="btn-close"
    data-bs-dismiss="alert"
    aria-label="Close"
  ></button>
</div>
{% elif category == 'warning' %}
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  {{ message }}
  <button
    type="button"
    class="btn-close"
    data-bs-dismiss="alert"
    aria-label="Close"
  ></button>
</div>
{% else %}
<div class="alert alert-success alert-dismissible fade show" role="alert">
  {{ message }}
  <button
    type="button"
    class="btn-close"
    data-bs-dismiss="alert"
    aria-label="Close"
  ></button>
</div>
{% endif %} {% endfor %} {% endif %} {% endwith %}

application/templates/layouts/partials/navbar.html
<!-- navbar navigation component -->
<nav class="navbar navbar-expand-lg navbar-white bg-white">
  <button type="button" id="sidebarCollapse" class="btn btn-light">
    <i class="fas fa-bars"></i><span></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="nav navbar-nav ms-auto">
      <li class="nav-item dropdown">
        <div class="nav-dropdown">
          <a
            href="#"
            id="nav2"
            class="nav-item nav-link dropdown-toggle text-secondary"
            data-bs-toggle="dropdown"
            aria-expanded="false"
          >
            {% if current_user.is_authenticated %}
            <i class="fas fa-user"></i>
            <span
              >{{ current_user.first_name }} {{ current_user.last_name }}</span
            >
            {% else %}
            <i class="fas fa-user"></i> <span>Not logged in</span>
            {% endif %}
            <i style="font-size: 0.8em" class="fas fa-caret-down"></i>
          </a>
          <div class="dropdown-menu dropdown-menu-end nav-link-menu">
            <ul class="nav-list">
              <li>
                <a href="{{ url_for('home.profile') }}" class="dropdown-item"
                  ><i class="fas fa-address-card"></i> Profile</a
                >
              </li>
              <li>
                <a
                  href="{{ url_for('home.messages_page') }}"
                  class="dropdown-item"
                  ><i class="fas fa-envelope"></i> Messages</a
                >
              </li>
              <li>
                <a
                  href="{{ url_for('home.change_password') }}"
                  class="dropdown-item"
                  ><i class="fas fa-cog"></i> Change Password</a
                >
              </li>
              <div class="dropdown-divider"></div>
              <li>
                <a
                  href="{{ url_for('auth.logout_handler') }}"
                  class="dropdown-item"
                  ><i class="fas fa-sign-out-alt"></i> Logout</a
                >
              </li>
            </ul>
          </div>
        </div>
      </li>
    </ul>
  </div>
</nav>
<!-- end of navbar navigation -->

application/templates/layouts/partials/sidebar.html
<nav id="sidebar" class="active">
  <div class="sidebar-header">
    <img
      src="{{url_for('static', filename='img/logo-grey.png')}}"
      alt="bootraper logo"
      class="app-logo nav-logo"
    />
  </div>
  <ul class="list-unstyled components text-secondary">
    <li>
      <a href="{{ url_for('home.dashboard_page') }}"
        ><i class="fas fa-home"></i> Dashboard</a
      >
    </li>
    <li>
      <a href="{{ url_for('post.list_posts') }}"
        ><i class="fas fa-list-alt"></i> Posts</a
      >
    </li>
    <li>
      <a href="{{ url_for('user.list_users') }}"
        ><i class="fas fa-users"></i> Users</a
      >
    </li>
    <li>
      <a href="{{ url_for('home.messages_page') }}"
        ><i class="fas fa-envelope"></i> Messages</a
      >
    </li>
  </ul>
</nav>